# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.geodesic <- function(lon1, lat1, azi1, s12, a, f) {
    .Call(`_geosphere_geodesic`, lon1, lat1, azi1, s12, a, f)
}

.inversegeodesic <- function(lon1, lat1, lon2, lat2, a, f) {
    .Call(`_geosphere_inversegeodesic`, lon1, lat1, lon2, lat2, a, f)
}

.polygonarea <- function(lon, lat, a, f) {
    .Call(`_geosphere_polygonarea`, lon, lat, a, f)
}

.geod_intermediate <- function(lon1, lat1, lon2, lat2, n, distance, arc, a, f) {
    .Call(`_geosphere_geodesic_nodes`, lon1, lat1, lon2, lat2, n, distance, arc, a, f)
}

